<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
>
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.mallcloud</groupId>
        <artifactId>coupon-service</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>coupon-biz</artifactId>
    <packaging>jar</packaging>
    <name>coupon-biz</name>
    <description>
        业务微服务聚合模块：统一管理所有业务微服务子模块，包含用户、商品、订单、支付、库存、物流、购物车、
        优惠券、促销、推荐、搜索、评价、通知、聊天及认证等核心业务服务
    </description>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
        </dependency>

        <dependency>
            <groupId>com.mallcloud</groupId>
            <artifactId>coupon-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mallcloud</groupId>
            <artifactId>commons-mybatis</artifactId>
        </dependency>
    </dependencies>
</project>
