# 开发环境日志级别：详细
logging:
  level:
    root: INFO
    com.mallcloud: INFO
    # 打印 SQL 语句
    com.mallcloud.**.mapper: DEBUG

# 开发环境 Admin 监控
management:
  boot:
    admin:
      client:
        url: http://localhost:9090