spring:
  cache:
    type: redis
  data:
    redis:
      host: 192.168.56.10
      password: 479368
  jackson:
    # 设置所在地区，不写则默认更具系统获取
    locale: zh_CN
    # 设置所在时区
    time-zone: GMT+8
    # 全局设置@JsonFormat的格式pattern
    date-format: yyyy-MM-dd HH:mm:ss

  security:
    oauth2:
      # OAuth2 客户端的配置信息，配置参考官方文档： https://docs.spring.io/spring-security/reference/servlet/oauth2/index.html
      client:
        # 配置第三方登录的客户端信息
        registration:
          # 唯一标识客户注册的 ID。
          gitee:
            provider: gitee
            # 客户标识符。
            client-id: your-gitee-client-id
            # 客户密钥。
            client-secret: your-gitee-client-secret
            # 客户认证方法。是一个枚举类型，包括 client_secret_post 和 private_key_jwt 等
            client-authentication-method: client_secret_post
            # 授权类型。是一个枚举类型，包括 authorization_code、client_credentials、password 以及扩展授权类型 jwt-bearer 等
            authorization-grant-type: authorization_code
            # 授权回调地址，必须与第三方登录的回调地址一致。
            redirect-uri: http://localhost:9001/auth/oauth2/code/gitee/callback
            # 客户端在授权请求流程中请求的范围，如 openid、电子邮件或个人资料。
            scope:
              - user_info
              - email
              - repos
              - issues
            # 用于客户端的描述性名称。该名称可在某些情况下使用，例如在自动生成的登录页面中显示客户名称时。
            client-name: Gitee
          # 唯一标识客户注册的 ID。
          github:
            provider: github
            # 客户标识符。
            clientId: your-github-client-id
            # 客户密钥。
            clientSecret: your-github-client-secret
            # 客户认证方法。是一个枚举类型，包括 client_secret_post 和 private_key_jwt 等
            client-authentication-method: client_secret_post
            # 授权类型。是一个枚举类型，包括 authorization_code、client_credentials、password 以及扩展授权类型 jwt-bearer 等
            authorization-grant-type: authorization_code
            # 授权回调地址，必须与第三方登录的回调地址一致。
            redirect-uri: http://localhost:9001/auth/oauth2/code/github/callback
            # 客户端在授权请求流程中请求的范围，如 openid、电子邮件或个人资料。
            scope:
              - user
              - user:email
              - user:follow
            # 用于客户端的描述性名称。该名称可在某些情况下使用，例如在自动生成的登录页面中显示客户名称时。
            client-name: Github
          # 唯一标识客户注册的 ID。
          qq:
            provider: qq
            # 客户标识符。
            clientId: your-qq-client-id
            # 客户密钥。
            clientSecret: your-qq-client-secret
            # 客户认证方法。是一个枚举类型，包括 client_secret_post 和 private_key_jwt 等
            client-authentication-method: client_secret_post
            # 授权类型。是一个枚举类型，包括 authorization_code、client_credentials、password 以及扩展授权类型 jwt-bearer 等
            authorization-grant-type: authorization_code
            # 授权回调地址，必须与第三方登录的回调地址一致。
            redirect-uri: http://localhost:9001/auth/oauth2/code/qq/callback
            # 客户端在授权请求流程中请求的范围，如 openid、电子邮件或个人资料。
            scope:
              - user
              - user_follow
              - user_info
            # 用于客户端的描述性名称。该名称可在某些情况下使用，例如在自动生成的登录页面中显示客户名称时。
            client-name: QQ
          # 唯一标识客户注册的 ID。
          wechat:
            provider: wechat
            # 客户标识符。
            clientId: your-wechat-client-id
            # 客户密钥。
            clientSecret: your-wechat-client-secret
            # 客户认证方法。是一个枚举类型，包括 client_secret_post 和 private_key_jwt 等
            client-authentication-method: client_secret_post
            # 授权类型。是一个枚举类型，包括 authorization_code、client_credentials、password 以及扩展授权类型 jwt-bearer 等
            authorization-grant-type: authorization_code
            # 授权回调地址，必须与第三方登录的回调地址一致。
            redirect-uri: http://localhost:9001/auth/oauth2/code/wechat/callback
            # 客户端在授权请求流程中请求的范围，如 openid、电子邮件或个人资料。
            scope:
              - snsapi_login
              - snsapi_userinfo
              - snsapi_base
              - snsapi_privateinfo
            # 用于客户端的描述性名称。该名称可在某些情况下使用，例如在自动生成的登录页面中显示客户名称时。
            client-name: WeChat
        # 第三方登录的配置信息
        provider:
          gitee:
            # 授权服务器的授权端点 URI。
            authorization-uri: https://gitee.com/oauth/authorize
            # 授权服务器的令牌端点 URI。
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-info-authentication-method: form
            user-name-attribute: sub
            # 用于从授权服务器检索 JSON 网络密钥（JWK）集的 URI，其中包含用于验证 ID 令牌的 JSON 网络签名（JWS）和（可选）用户信息回复的加密密钥。
            jwk-set-uri: https://gitee.com/oauth/jwkset
            # 返回 OpenID Connect 1.0 提供商或 OAuth 2.0 授权服务器的发行方标识符 URI。
            issuer-uri: https://gitee.com/oauth/
          github:
            # 授权服务器的授权端点 URI。
            authorization-uri: https://gitee.com/oauth/authorize
            # 授权服务器的令牌端点 URI。
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-info-authentication-method: form
            user-name-attribute: sub
            # 用于从授权服务器检索 JSON 网络密钥（JWK）集的 URI，其中包含用于验证 ID 令牌的 JSON 网络签名（JWS）和（可选）用户信息回复的加密密钥。
            jwk-set-uri: https://gitee.com/oauth/jwkset
            # 返回 OpenID Connect 1.0 提供商或 OAuth 2.0 授权服务器的发行方标识符 URI。
            issuer-uri: https://gitee.com/oauth/
          qq:
            # 授权服务器的授权端点 URI。
            authorization-uri: https://gitee.com/oauth/authorize
            # 授权服务器的令牌端点 URI。
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-info-authentication-method: form
            user-name-attribute: sub
            # 用于从授权服务器检索 JSON 网络密钥（JWK）集的 URI，其中包含用于验证 ID 令牌的 JSON 网络签名（JWS）和（可选）用户信息回复的加密密钥。
            jwk-set-uri: https://gitee.com/oauth/jwkset
            # 返回 OpenID Connect 1.0 提供商或 OAuth 2.0 授权服务器的发行方标识符 URI。
            issuer-uri: https://gitee.com/oauth/
          wechat:
            # 授权服务器的授权端点 URI。
            authorization-uri: https://gitee.com/oauth/authorize
            # 授权服务器的令牌端点 URI。
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-info-authentication-method: form
            user-name-attribute: sub
            # 用于从授权服务器检索 JSON 网络密钥（JWK）集的 URI，其中包含用于验证
            jwk-set-uri: https://gitee.com/oauth/jwkset
            # 返回 OpenID Connect 1.0 提供商或 OAuth 2.0 授权服务器的发行方标识符 URI。
            issuer-uri: https://gitee.com/oauth/
      # OAuth2 资源服务器的配置信息
      resourceserver:
        jwt:
          jwk-set-uri: https://cnbj1.fds.api.xiaomi.com/mi-files/v1/rest/jwt/public_key?appId=1400603526&timestamp=1620000000&nonce=1234567890&signature=1234567890
          jws-algorithms: [ RS256 ]
          issuer-uri: https://cnbj1.fds.api.xiaomi.com
          public-key-location: banner.txt
          audiences: justauth
          authority-prefix: ROLE_
          authorities-claim-delimiter: ,
          authorities-claim-name: authorities
          principal-claim-name: username
        opaquetoken:
          client-id: justauth
          client-secret: justauth
          introspection-uri: https://cnbj1.fds.api.xiaomi.com/mi-auth/v2/oauth2/introspect

  # QQ 邮箱配置
  mail:
    host: smtp.qq.com
    port: 465
    username: your-email-address
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

aliyun:
  oss:
    access-id:
    secret-key:
    endpoint: oss-cn-shanghai.aliyuncs.com
    bucket: lilongfa-gulimall
    expire-time: 600

tencent:
  sms:
    secret-id:
    secret-key:
    sdk-app-id: 1400603526
    sign-name: 龙茶清欢
    template-id: 1222991
    timeout: 10

# 腾讯邮箱 签名授权  tfrbdtufrryyebeh

justauth:
  enabled: true
  type:
    GITEE:
      client-id: cc7e60321f8cf20c601ddda24a49ca7d0e0561e3523f6f7d89ebbe8d903bba0a
      client-secret: 0346479cb383faaba032e80a4095ec282b49220061b64a729a92ded6720757d9
      redirect-uri: http://localhost:9001/auth/gitee/callback
    GITHUB:
      client-id: cc7e60321f8cf20c601ddda24a49ca7d0e0561e3523f6f7d89ebbe8d903bba0a
      client-secret: 0346479cb383faaba032e80a4095ec282b49220061b64a729a92ded6720757d9
      redirect-uri: http://localhost:9001/auth/gitee/callback
    QQ:
      client-id: cc7e60321f8cf20c601ddda24a49ca7d0e0561e3523f6f7d89ebbe8d903bba0a
      client-secret: 0346479cb383faaba032e80a4095ec282b49220061b64a729a92ded6720757d9
      redirect-uri: http://localhost:9001/auth/gitee/callback


  boot:
    admin:
      client:
        url: http://localhost:9003

