<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.mallcloud</groupId>
        <artifactId>mall-cloud</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>commons</artifactId>
    <packaging>pom</packaging>
    <name>commons</name>
    <description>
        公共基础模块聚合：统一管理所有公共基础设施子模块，包含核心工具、数据模型、缓存、安全、
        日志、接口文档、对象存储、MyBatis 扩展、定时任务、OpenAPI 及启动Banner自定义 等基础能力
    </description>

    <modules>
        <module>commons-banner</module>
        <module>commons-cache</module>
        <module>commons-core</module>
        <module>commons-job</module>
        <module>commons-logging</module>
        <module>commons-mybatis</module>
        <module>commons-openapi</module>
        <module>commons-oss</module>
        <module>commons-security</module>
    </modules>
</project>
