<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.mallcloud</groupId>
        <artifactId>user-service</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>user-biz</artifactId>
    <packaging>jar</packaging>
    <name>user-biz</name>
    <description>用户服务：负责用户基本信息管理、收货地址、会员等级、积分及账户安全等用户中心核心功能</description>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mallcloud</groupId>
            <artifactId>user-api</artifactId>
            <version>1.0.0</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>
