<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
>
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.mallcloud</groupId>
    <artifactId>commons</artifactId>
    <version>${revision}</version>
  </parent>
  <artifactId>commons-core</artifactId>
  <packaging>jar</packaging>
  <name>commons-core</name>
  <description
    >核心公共模块：提供全局异常处理、统一响应体封装、基础常量定义及各模块通用的核心基础能力</description>

  <dependencies>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
    </dependency>
    <dependency>
      <groupId>com.alibaba</groupId>
      <artifactId>fastjson</artifactId>
    </dependency>
      <dependency>
          <groupId>io.swagger.core.v3</groupId>
          <artifactId>swagger-annotations-jakarta</artifactId>
          <version>2.2.47</version>
          <scope>compile</scope>
      </dependency>
  </dependencies>
</project>
