# REST 客户端（ RestClient ）、HTTP 服务客户端（ @HttpExchange ）
# https://docs.springjava.cn/spring-framework/reference/integration/rest-clients.html
# https://docs.springjava.cn/spring-boot/reference/io/rest-client.html


