# 配置配置应用的常规、非敏感、不变动的属性
spring:
  cloud:
    gateway:
      # 网关全局跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-headers: "*"
            allowed-methods: "*"
            allowed-origins: "*"
            allowed-origin-patterns: "*"
            allow-credentials: true
        # 要为某些网关路由谓词未处理的请求提供相同的 CORS 配置，请执行以下操作：请将下面的属性设置为 true。当你尝试支持 CORS 预检请求，但由于 HTTP 方法是选项，你的路由谓词无法评估为 true 时，这就非常有用了。
        add-to-simple-url-handler-mapping: true
      # 网关路由配置
      routes:
        - id: blog-cloud-auth
          # 如果 URL 采用 lb 方案（如 lb://blog-cloud-auth），则会使用 Spring Cloud ReactorLoadBalancer 将名称（本例中为 blog-cloud-auth）解析为实际主机和端口，并在同一属性中替换 URI。
          uri: lb://blog-cloud-auth
          predicates:
            - Path=/auth/**
        - id: weight_high
          uri: https://weighthigh.org
          # 权重路由谓词工厂需要两个参数：组和权重（int）。权重按组计算
          predicates:
            - Weight=group1, 8
        - id: weight_low
          uri: lb://service
          predicates:
            - Weight=group1, 2
        # 路径路由谓词工厂需要一个 Spring PathMatcher 模式列表
        # 该路由匹配： /red/1 或 /red/1/ 或 /red/blue 或 /blue/green。等格式
        - id: path_route
          uri: https://example.org
          predicates:
            - Path=/red/{segment},/blue/{segment}
        # RewritePath GatewayFilter 工厂需要一个路径 regexp 参数和一个替换参数。它使用 Java 正则表达式，以灵活的方式重写请求路径
        # 如果请求路径为 /red/blue，则在发出下游请求前将路径设置为 /blue。注意，剔除请求路径中的前缀 /red
        - id: rewritepath_route
          uri: https://example.org
          predicates:
            - Path=/red/**
          filters:
            - RewritePath=/red/?(?<segment>.*), /$\{segment}
        # PrefixPath GatewayFilter（前缀路径网关过滤器）工厂只接受一个前缀参数。它将请求路径的前缀添加到 URI 路径中。
        # 这样，/mypath 就成为所有匹配请求的路径前缀。因此，向 /hello 提出的请求会被发送到 /mypath/hello。
        - id: prefixpath_route
          uri: https://example.org
          filters:
            - PrefixPath=/mypath
        # StripPrefix GatewayFilter 工厂需要一个参数，即部件。部件参数表示在向下游发送请求前要从路径中剥离的部件数量
        # 当通过网关向 /name/blue/red 提出请求时，向 nameservice 提出的请求看起来就像 nameservice/red。移除指定数量的前缀部件
        - id: nameRoot
          uri: https://nameservice
          predicates:
            - Path=/name/**
          filters:
            - StripPrefix=2
        # RequestRateLimiter GatewayFilter 工厂使用 RateLimiter 实现来确定当前请求是否允许继续。如果不允许，就会返回 HTTP 429 状态--请求过多（默认）。
        # 该过滤器需要一个 key-resolver 参数，它是一个 Bean 名称或 Bean 类型，用于确定请求的唯一标识符。
        # keyResolver 是一个实现 KeyResolver 接口的 Bean。在配置中，使用 SpEL 通过名称引用 Bean。#{@myKeyResolver} 是引用名为 myKeyResolver 的 Bean 的 SpEL 表达式。
        # 限流路由过滤器使用参考： https://docs.spring.io/spring-cloud-gateway/reference/spring-cloud-gateway/gatewayfilter-factories/requestratelimiter-factory.html
        - id: limit
          uri: https://example.org
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userkeyresolver}"
        # 直接使用 RedissonRateLimiter 实现来实现限流。该实现需要一个 RedissonClient 实例，用于连接 Redis 数据库。
        - id: requestratelimiter_route
          uri: https://example.org
          filters:
            - name: RequestRateLimiter
              args:
                # 定义了每秒允许多少个请求（不包括掉线请求）。这是令牌桶的填充速度。
                redis-rate-limiter.replenishRate: 10
                # 定义了单个用户在一秒钟内允许的最大请求数（不包括任何放弃的请求）。这是令牌桶可容纳的令牌数量。将此值设为零会阻止所有请求。
                redis-rate-limiter.burstCapacity: 20
                # 定义了一个请求需要多少代币。这是每个请求从桶中取出的代币数量，默认为 1。也就是每一个请求都会消耗一个代币。一般不用设置
                redis-rate-limiter.requestedTokens: 1
        # 自定义限流器实现。该实现需要一个 RateLimiter 接口的 Bean。
        - id: requestratelimiter_route
          uri: https://example.org
          filters:
            - name: RequestRateLimiter
              args:
                rate-limiter: "#{@myRateLimiter}"
                key-resolver: "#{@userKeyResolver}"
      # 网关http客户端配置
      httpclient:
        # 可为所有路由配置 Http 超时（响应和连接），也可为每个特定路由设置超时。
        # 配置全局 http 超时：
        connect-timeout: 1000   # 必须以毫秒为单位。
        response-timeout: 5s
        # 关于 gateway 配置 TLS 和 SSL 的配置参考： https://docs.spring.io/spring-cloud-gateway/reference/spring-cloud-gateway/tls-and-ssl.html
        ssl:
          # 您可以将网关路由路由到 HTTP 和 HTTPS 后端。如果要路由到 HTTPS 后端，可以通过以下配置将网关配置为信任所有下游证书：
          useInsecureTrustManager: true
          # 使用不安全的信任管理器不适合生产。在生产部署中，可以通过以下配置为网关配置一组它可以信任的已知证书：
          # 如果 Spring Cloud Gateway 未配置受信任的证书，则会使用默认信任存储（可通过设置 javax.net.ssl.trustStore 系统属性来覆盖）。
          trustedX509Certificates:
            - cert1.pem
            - cert2.pem
          # 如果要配置自定义证书，请使用以下配置：
          key-store: classpath:scg-keystore.p12
          key-store-type: PKCS12
          key-store-password: scg1234
          handshake-timeout: 10s
          close-notify-flush-timeout: 3s
          close-notify-read-timeout: 0s